export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  verifyEmail: '/auth/verify-email',
  terms: '/terms',
  privacy: '/privacy',
  onboarding: '/onboarding',
  widget: '/widget',

  bonds: '/bonds',
  bondDetail: (internalId: string) => `/bonds/${encodeURIComponent(internalId)}`,
  bondDetailPattern: '/bonds/:internalId',
  companies: '/companies',
  companyDetail: (issuer: string) => `/companies/${encodeURIComponent(issuer)}`,
  companyDetailPattern: '/companies/:issuer',
  stocks: '/stocks',
  stockDetail: (internalId: string) => `/stocks/${encodeURIComponent(internalId)}`,
  stockDetailPattern: '/stocks/:internalId',
  news: '/news',
  recommendations: '/recommendations',
  scores: '/scores',
  analytics: '/analytics',
  desk: '/desk',
  portfolio: '/portfolio',
  portfolioAdvanced: '/portfolio/advanced',
  forecast: '/forecast',
  alerts: '/alerts',
  calculator: '/calculator',
  documents: '/documents',
  chat: '/chat',
  account: '/account',
  subscribe: '/subscribe',
} as const;
