"""
Fix missing auto-increment on alert_rules.id / alert_events.id (PostgreSQL).

Migration 0008 declared BigInteger PK columns without IDENTITY/sequence. On
SQLite INTEGER PRIMARY KEY auto-generates, masking the bug; on PostgreSQL every
insert into alert_rules/alert_events fails with a NOT NULL violation for id.
The ORM declares autoincrement=True (scraper/orm.py), so the fix here is to
convert the PKs to GENERATED BY DEFAULT AS IDENTITY on PostgreSQL. SQLite
already works and its DDL can't express IDENTITY, so it's a no-op there.

Revision ID: 0024_alert_pk_identity
Revises: 0023_predictions_unique
Create Date: 2026-08-02
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "0024_alert_pk_identity"
down_revision = "0023_predictions_unique"
branch_labels = None
depends_on = None


def upgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    # Idempotent guards: multiple containers may race `alembic upgrade head`
    # (each service runs migrations at startup), and a rerun must not fail on
    # a column that already has an identity/sequence default.
    for table, column in (("alert_rules", "id"), ("alert_events", "id")):
        has_identity = op.get_bind().execute(
            sa.text(
                """
                SELECT 1 FROM pg_attribute
                WHERE attrelid = to_regclass(:table)
                  AND attname = :column
                  AND attidentity <> ''
                LIMIT 1
                """
            ),
            {"table": table, "column": column},
        ).first()
        has_default = op.get_bind().execute(
            sa.text(
                """
                SELECT 1 FROM pg_attrdef d
                JOIN pg_attribute a ON a.attrelid = d.adrelid
                                    AND a.attnum = d.adnum
                WHERE a.attrelid = to_regclass(:table)
                  AND a.attname = :column
                LIMIT 1
                """
            ),
            {"table": table, "column": column},
        ).first()
        if has_identity:
            continue
        if has_default:
            # A sequence default exists but no identity — convert the default
            # off first so ADD GENERATED works on PG < 15.
            op.execute(
                f"ALTER TABLE {table} ALTER COLUMN {column} DROP DEFAULT;"
            )
        op.execute(
            f"""
            ALTER TABLE {table}
            ALTER COLUMN {column} ADD GENERATED BY DEFAULT AS IDENTITY;
            """
        )
        op.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{table}', '{column}'),
                COALESCE((SELECT MAX({column}) FROM {table}), 0) + 1,
                false
            );
            """
        )


def downgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute("ALTER TABLE alert_events ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE alert_rules ALTER COLUMN id DROP IDENTITY IF EXISTS;")
