"""
Fix missing auto-increment on alert_rules.id / alert_events.id (PostgreSQL).

Migration 0008 declared BigInteger PK columns without IDENTITY/sequence. On
SQLite INTEGER PRIMARY KEY auto-generates, masking the bug; on PostgreSQL every
insert into alert_rules/alert_events fails with a NOT NULL violation for id.
The ORM declares autoincrement=True (scraper/orm.py), so the fix here is to
convert the PKs to GENERATED BY DEFAULT AS IDENTITY on PostgreSQL. SQLite
already works and its DDL can't express IDENTITY, so it's a no-op there.

Revision ID: 0024_alert_pk_identity
Revises: 0023_predictions_unique
Create Date: 2026-08-02
"""

from __future__ import annotations

from alembic import op

revision = "0024_alert_pk_identity"
down_revision = "0023_predictions_unique"
branch_labels = None
depends_on = None


def upgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    # GENERATED BY DEFAULT keeps existing values valid and assigns new ones on
    # insert; the implicit sequence starts at 1 and may collide with existing
    # rows, so seed it past the current max.
    op.execute(
        """
        ALTER TABLE alert_rules
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('alert_rules', 'id'),
            COALESCE((SELECT MAX(id) FROM alert_rules), 0) + 1,
            false
        );
        """
    )
    op.execute(
        """
        ALTER TABLE alert_events
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('alert_events', 'id'),
            COALESCE((SELECT MAX(id) FROM alert_events), 0) + 1,
            false
        );
        """
    )


def downgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute("ALTER TABLE alert_events ALTER COLUMN id DROP IDENTITY IF EXISTS;")
    op.execute("ALTER TABLE alert_rules ALTER COLUMN id DROP IDENTITY IF EXISTS;")
